const fs=require('fs'),assert=require('assert'),vm=require('vm');
const html=fs.readFileSync('index.html','utf8');
const match=html.match(/<script\s*>([\s\S]*?)<\/script>/);
assert(match,'Script principal ausente');
const src=match[1];
for(const name of ['fileSignature','fileWriteAllowed','fileUnchanged','writeDataFile','finishFileSave','saveDataFile','autoSaveDataFile','saveAsDataFile','openDataFile','atualizarAplicativo','atualizarSemSalvar','salvarEAtualizar','setFileAccessState'])assert(src.includes('function '+name+'('),'Função ausente: '+name);
for(const token of ['indexedDB','localStorage','persistLocalSession','restoreLocalSession','localSet(','localGet(','downloadDataFile(','scheduleLocalSave('])assert(!src.includes(token),'Persistência no navegador proibida: '+token);
assert(src.includes("window.addEventListener('beforeunload'"),'F5 precisa proteger alterações pendentes');
assert(src.includes('queueFileSave(handle,false)'),'Autosave apenas com permissao existente');
assert(src.includes("new Blob([content],{type:'application/json;charset=utf-8'})"),'Salvamento deve calcular o tamanho real em bytes');
assert(src.includes("writable.write({type:'write',position:0,data:blob})"),'Salvamento deve reescrever desde o início');
assert(src.includes('await writable.truncate(blob.size)'),'Salvamento deve remover bytes antigos que possam sobrar no fim');
assert(src.includes('function recuperarJsonComFechamentoExtra('),'Abertura deve recuperar apenas fechamento extra no fim');
assert(src.includes("setSaveStatus('Não salvo — JSON recuperado; salve para corrigir.')"),'JSON recuperado precisa exigir nova gravação');
assert(src.includes('fileWriteAllowed(handle,askPermission)'),'Salvar precisa permitir autorizacao por clique');
for(const id of ['refresh-overlay','refresh-save','refresh-discard','refresh-cancel','refresh-file-name'])assert(html.includes('id="'+id+'"'),'Ação do diálogo ausente: '+id);
assert(html.includes('Salvar e atualizar')&&html.includes('Atualizar sem salvar'),'Opções de atualização incompletas');
assert(!/(?<![\w.])(?:alert|confirm|prompt)\s*\(/.test(src),'Proibido usar alert/confirm/prompt nativos');
assert(src.includes('setFileAccessState(false)'),'O site deve iniciar sem documento ativo');
assert(!src.includes('void restoreLocalSession()'),'Proibido restaurar sessão anterior');
function fn(name){const re=new RegExp('^(?:async )?function '+name+'\\([^\\n]*\\)\\{.*?^\\}\\n','ms');const m=src.match(re);assert(m,'Não extraiu '+name);return m[0];}
let timer=0,write=0,permission=[];
const ctx=vm.createContext({console,Promise,Error,Date,Number,String,JSON,setTimeout:(f,n)=>{timer=n;return 1},clearTimeout:()=>{},fileWriteAllowed:async(h,ask)=>{permission.push(ask);return true;},fileUnchanged:async()=>true,writeDataFile:async()=>{write++;return 1;},finishFileSave:async()=>{vm.runInContext('hasUnsavedChanges=false',ctx);return true;},setSaveStatus:()=>{}});
vm.runInContext('let dataFileHandle=null,hasUnsavedChanges=false,appReady=true,isApplyingData=false,dataRevision=0,diskSaveTimer=null,fileSaveQueue=Promise.resolve();'+fn('saveData')+fn('queueFileSave')+fn('autoSaveDataFile'),ctx);
vm.runInContext('saveData()',ctx);
assert.strictEqual(vm.runInContext('hasUnsavedChanges',ctx),false,'Sem arquivo nao ha alteracoes permitidas');
vm.runInContext("dataFileHandle={name:'teste.json'};saveData()",ctx);
assert.strictEqual(vm.runInContext('hasUnsavedChanges',ctx),true);
assert.strictEqual(timer,10000,'Somente JSON em 10 segundos');
(async()=>{await vm.runInContext('autoSaveDataFile()',ctx);assert.deepStrictEqual(permission,[false]);assert.strictEqual(write,1);assert.strictEqual(vm.runInContext('hasUnsavedChanges',ctx),false);console.log('PASS: JSON exclusivo, bloqueio sem arquivo, autosave autorizado, aviso F5 e diálogo de atualização');})().catch(e=>{console.error(e);process.exitCode=1});
