const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const body=html.match(/<script\s*>([\s\S]*?)<\/script>/);
assert(body,'Script principal não encontrado');
fs.writeFileSync('/tmp/meu-dinheiro-validar.js',body[1]);
function get(name){
 const start=body[1].indexOf('function '+name+'(');
 assert(start>=0,'Função ausente: '+name);
 const end=body[1].indexOf('\nfunction ',start+10);
 return body[1].slice(start,end<0?body[1].length:end);
}
const names=['isoDate','monthKey','valorMonetarioValido','valorParcela','novoIdExtrato','saldoInicialValido','calcularSaldoDisponivelAte','receitaReal','movimentoRealizado','dueDateFor','getMesMap','getParcelasCartao','pagoNaFatura','totalDaFatura','reservadoEmMetas','dataISOValida','validarDadosImportados','escHtml'];
const env=vm.createContext({console,Date,Set,Number,Math,String,Array,Error});
vm.runInContext("let hoje='2026-09-19';function today(){return hoje;} const S={extrato:[],cartao:[],invest:[],cartoes:[],saldoInicial:null};const MESES=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];"+names.map(get).join('\n'),env);
const run=x=>vm.runInContext(x,env);
assert.strictEqual(run('calcularSaldoDisponivelAte(today())'),null);
run("S.saldoInicial={valor:1000,data:'2026-09-19',idsIgnorados:['1']};S.extrato=[{id:1,data:'2026-09-19',tipo:'entrada',val:999},{id:2,data:'2026-09-20',tipo:'entrada',val:200},{id:3,data:'2026-09-19',tipo:'saida',val:50},{id:4,data:'2026-09-19',tipo:'entrada',categoria:'Resgate',val:20}]");
assert.strictEqual(run('calcularSaldoDisponivelAte(today())'),970);
run("hoje='2026-09-20'");
assert.strictEqual(run('calcularSaldoDisponivelAte(today())'),1170);
assert.strictEqual(run("calcularSaldoDisponivelAte('2026-09-18')"),null);
assert.strictEqual(run("receitaReal({tipo:'entrada',categoria:'Resgate'})"),false);
assert.strictEqual(run("receitaReal({tipo:'entrada',categoria:'Trabalho'})"),true);
assert.strictEqual(run('valorParcela({val:100,parcelas:3},0)'),33.34);
assert.strictEqual(run('valorParcela({val:100,parcelas:3},1)'),33.33);
assert.strictEqual(run('valorParcela({val:100,parcelas:3},2)'),33.33);
assert.strictEqual(run('[0,1,2].reduce((t,i)=>t+Math.round(valorParcela({val:100,parcelas:3},i)*100),0)'),10000);
assert.strictEqual(run("isoDate(...[2026,8,dueDateFor(new Date('2026-09-04T12:00:00'),12,0,5).getDate()])"),'2026-09-12');
assert.strictEqual(run("dueDateFor(new Date('2026-09-06T12:00:00'),12,0,5).getMonth()"),9);
assert.strictEqual(run("dueDateFor(new Date('2026-09-24T12:00:00'),5,0,25).getMonth()"),9);
assert.strictEqual(run("dueDateFor(new Date('2026-09-26T12:00:00'),5,0,25).getMonth()"),10);
run("S.cartao=[{id:5,cardId:7,data:'2026-09-06',val:100,parcelas:3,vencDia:12,closeDay:5}];S.extrato=[{id:8,tipo:'saida',cardId:7,faturaMes:'2026-10',val:20}]");
assert.strictEqual(run("totalDaFatura(7,'2026-10')"),3334);
assert.strictEqual(run("pagoNaFatura(7,'2026-10')"),2000);
assert.strictEqual(run("totalDaFatura(7,'2026-10')-pagoNaFatura(7,'2026-10')"),1334);
run("S.invest=[{id:1,kind:'investimento',valorAtual:200},{id:2,kind:'meta',storageId:1,valorAtual:150}]");
assert.strictEqual(run('reservadoEmMetas(1)'),150);
assert.strictEqual(run("dataISOValida('2026-02-30')"),false);
assert.strictEqual(run("dataISOValida('2026-02-28')"),true);
assert.strictEqual(run("escHtml('<img src=x onerror=alert(1)>')"),'&lt;img src=x onerror=alert(1)&gt;');
const valid="{extrato:[{id:1,data:'2026-09-19',tipo:'entrada',val:100}],cartao:[],invest:[],cartoes:[]}";
assert.strictEqual(run('validarDadosImportados('+valid+').extrato.length'),1);
assert.throws(()=>run("validarDadosImportados({extrato:[{id:1,data:'2026-02-30',tipo:'entrada',val:10}],cartao:[],invest:[],cartoes:[]})"));
assert.throws(()=>run("validarDadosImportados({extrato:[{id:1,data:'2026-09-19',tipo:'entrada',val:10},{id:1,data:'2026-09-19',tipo:'saida',val:10}],cartao:[],invest:[],cartoes:[]})"));
assert(html.includes('idsIgnorados:S.extrato.filter(x=>x.data<=today())'),'Saldo inicial precisa manter lançamentos futuros');
assert(html.includes('validarDadosImportados(parsed);')&&html.includes('dataFileHandle=handle;knownFileSignature='),'Arquivo só é associado após validação');
assert(html.includes('faturaMes:mes'),'Pagamentos vinculados à fatura');
assert(html.includes('S.extrato.some(x=>String(x.destId)===String(id))'),'Exclusão com proteção de histórico');
console.log('PASS: saldo, datas futuras, receitas/resgates, centavos, fechamento, faturas, metas, JSON, HTML e vínculos');
