const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('index.html','utf8');
const rec=fs.readFileSync('js/recorrentes.js','utf8');
const script=html.match(/<script\s*>([\s\S]*?)<\/script>/);
assert(script,'Script principal ausente');
const source=script[1];
const start=source.indexOf('function valorCartaoNoMes(');
const end=source.indexOf('\nfunction renderCartao(',start);
assert(start>=0&&end>start,'Calculo mensal isolado ausente');
const ctx=vm.createContext({Number,Math,String});
vm.runInContext(source.slice(start,end),ctx);
const sum=(items,parc)=>vm.runInContext('somarValoresCartaoNoMes('+JSON.stringify(items)+','+JSON.stringify(parc)+')',ctx);
const vista=[{id:1,val:80},{id:2,val:19.99}];
const parceladas=[{id:3,val:1348.38,parcelas:6},{id:4,val:180,parcelas:2}];
const mensal=[{id:'1-0',val:80},{id:'2-0',val:19.99},{id:'3-0',val:224.73},{id:'4-0',val:90}];
assert.strictEqual(sum(vista,mensal),99.99,'À vista usa o valor do mes');
assert.strictEqual(sum(parceladas,mensal),314.73,'Parcelamento usa parcela de 224,73 e 90, nao as compras integrais');
assert.strictEqual(sum(vista.concat(parceladas),mensal),414.72,'Total geral soma somente a coluna Valor');
const mesSeguinte=[{id:'3-1',val:224.73},{id:'4-1',val:90}];
assert.strictEqual(sum(parceladas,mesSeguinte),314.73,'Mes seguinte considera segunda parcela');
assert.strictEqual(sum(vista,mesSeguinte),0,'Nao repetir compras à vista em outros meses');
assert.strictEqual(sum([{id:30,val:100,parcelas:3}],[{id:'30-1',val:33.33}]),33.33,'Preservar centavos individuais da parcela');
assert(html.includes('<th style="width:75px">Parcelas</th><th style="width:110px">Valor</th>'),'Exatamente as colunas Parcelas e Valor');
assert(!html.includes('>Pagas</th>')&&!html.includes('>Valor total</th>')&&!html.includes('>Valor da parcela</th>'),'Remover colunas redundantes');
assert(!html.includes("qtdParcelas+'x'"),'Quadradinho substitui a antiga quantidade 6x');
assert(html.includes('class="cc-paid-status"')&&html.includes('colspan="7"'),'Progresso informativo permanece na coluna Parcelas');
assert(html.includes('Subtotal ${titulo} · valores do mês'),'Subtotais calculados sobre valor do mes');
assert(html.includes('Total exibido neste mês · pode incluir histórico'),'Total da tabela distingue historico da fatura');
assert(!html.includes('somarValoresTotaisCartao('),'Nao somar preco integral das compras');
const bodyStart=rec.indexOf('function renderRecurring(){'),bodyEnd=rec.indexOf('function saveRecEditor(',bodyStart);
assert(bodyStart>=0&&bodyEnd>bodyStart,'Renderizacao dos recorrentes ausente');
const body=rec.slice(bodyStart,bodyEnd);
assert(!body.includes('<div class="rec-item-bottom">'),'Extrato ainda tem terceira linha desnecessaria');
assert(body.split('<span class="rec-inline-actions">').length>=3,'Botoes no cabecalho de ambas as listas');
assert(body.includes('Dia do recebimento: ')&&body.includes('Dia da cobrança: '),'Distinguir entradas e saidas');
assert(rec.includes('#rec-list .rec-item{padding:8px 10px}')&&rec.includes('#rec-card-list .rec-item{padding:8px 10px}'),'Mesmo tamanho compacto');
console.log('PASS: coluna Valor mensal, parcelas em uma coluna, subtotais e total exatos, historico e recorrencia preservados');
