const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('index.html','utf8');
const rec=fs.readFileSync('js/recorrentes.js','utf8');
const script=html.match(/<script\s*>([\s\S]*?)<\/script>/);
assert(script,'Script principal ausente');
const source=script[1];
const start=source.indexOf('function somarValoresTotaisCartao(');
const end=source.indexOf('\nfunction renderCartao(',start);
assert(start>=0&&end>start,'Somatorio isolado de compras ausente');
const ctx=vm.createContext({Number,Math});
vm.runInContext(source.slice(start,end),ctx);
const sum=items=>vm.runInContext('somarValoresTotaisCartao('+JSON.stringify(items)+')',ctx);
const vista=[{val:80},{val:19.99}],parceladas=[{val:1348.38},{val:180}];
assert.strictEqual(sum(vista),99.99);
assert.strictEqual(sum(parceladas),1528.38);
assert.strictEqual(sum(vista.concat(parceladas)),1628.37,'Total integral da compra, nao apenas parcela de outubro');
assert(html.includes('Subtotal ${titulo} · valor integral das compras'),'Subtotal por grupo na coluna Valor total');
assert(html.includes('Total dos valores integrais exibidos · não é a fatura do mês'),'Total geral distinto da fatura');
assert(html.includes('cc-group-subtotal')&&html.includes('cc-grand-total'),'Estilos dos totais ausentes');
const bodyStart=rec.indexOf('function renderRecurring(){'),bodyEnd=rec.indexOf('function saveRecEditor(',bodyStart);
assert(bodyStart>=0&&bodyEnd>bodyStart,'Renderizacao dos recorrentes ausente');
const body=rec.slice(bodyStart,bodyEnd);
assert(!body.includes('<div class="rec-item-bottom">'),'Extrato ainda tem terceira linha desnecessaria');
assert(body.split('<span class="rec-inline-actions">').length>=3,'Botoes precisam estar no cabecalho de ambas as listas');
assert(body.includes('Dia do recebimento: ')&&body.includes('Dia da cobrança: '),'Distinguir entradas e saidas');
assert(rec.includes('#rec-list .rec-item{padding:8px 10px}')&&rec.includes('#rec-card-list .rec-item{padding:8px 10px}'),'Mesmo tamanho compacto nas duas abas');
console.log('PASS: layout Extrato = Cartao, totais por grupo e geral, centavos exatos e fatura preservada');
