const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('index.html','utf8');
const script=html.match(/<script\s*>([\s\S]*?)<\/script>/);
assert(script,'Script principal ausente');
function fn(name){
 const src=script[1],start=src.indexOf('function '+name+'(');
 assert(start>=0,'Funcao ausente: '+name);
 const rest=src.slice(start+10),next=/\n(?:async )?function [A-Za-z]/.exec(rest);
 return src.slice(start,next?start+10+next.index:src.length);
}
const names=['isoDate','monthKey','valorParcela','dueDateFor','vencimentoDaCompra','getParcelasCartao','totalDaFatura','parcelasPagasPorFaturas','parcelasHistoricasConfirmadas','parcelasPagasConfirmadas','dataISOValida','saldoInicialValido','validarDadosImportados'];
const ctx=vm.createContext({console,Date,Set,Number,Math,String,Array,Error});
vm.runInContext("const S={cartao:[],cartoes:[],extrato:[],invest:[],saldoInicial:{valor:1000,data:'2026-09-18',idsIgnorados:[]}};let hoje='2026-09-20';function today(){return hoje;};"+names.map(fn).join('\n'),ctx);
const run=code=>vm.runInContext(code,ctx);
assert(html.includes('id="cc-mes"')&&html.includes('#cc-mes{color:#f2b75e'),'Fatura do mes precisa de contraste mais claro');
assert(html.includes('>Pagas</th>')&&html.includes('class="cc-paid-status"')&&!html.includes('onclick="editarParcelasPagas(${r.id})"')&&html.includes('colspan="9"'),'Pagas deve ser texto nao clicavel, com agrupamento sincronizado');
for(const id of ['card-paid-editor','card-paid-count','card-paid-form'])assert(html.includes('id="'+id+'"'),'Dialogo ausente: '+id);
run("S.cartoes=[{id:1,bank:'Itaú',dueDay:10}];S.cartao=[{id:101,cardId:1,data:'2026-09-02',desc:'Hotel',val:1348.38,parcelas:6,vencDia:10,closeDay:null,tipo:'parcelado'}]");
assert.strictEqual(run('parcelasPagasConfirmadas(S.cartao[0])'),1,'Hotel pago antes da abertura: 1 de 6, sem clique');
run('S.cartao[0].parcelasPagasInformadas=1');
assert.strictEqual(run('parcelasPagasConfirmadas(S.cartao[0])'),1,'Preservar valor historico antigo do JSON');
run("S.cartao.push({id:102,cardId:1,data:'2026-08-25',desc:'Panelas',val:774,parcelas:4,vencDia:24,closeDay:null,tipo:'parcelado'})");
assert.strictEqual(run('parcelasPagasConfirmadas(S.cartao[1])'),1,'Compra de agosto com primeira fatura em setembro ja paga, mesmo antecipadamente');
run("S.cartao.push({id:103,cardId:1,data:'2026-08-15',desc:'Tenis',val:960,parcelas:10,vencDia:10,closeDay:null,tipo:'parcelado'})");
assert.strictEqual(run('parcelasPagasConfirmadas(S.cartao[2])'),1,'Compra de agosto com vencimento dia 10: 1 de 10');
run("S.cartao.push({id:104,cardId:1,data:'2026-09-19',desc:'Compra nova',val:300,parcelas:3,vencDia:10,closeDay:null,tipo:'parcelado'})");
assert.strictEqual(run('parcelasPagasConfirmadas(S.cartao[3])'),0,'Compra depois da abertura so confirma mediante pagamento');
run("hoje='2026-10-15'");
assert.strictEqual(run('parcelasPagasConfirmadas(S.cartao[1])'),1,'Passagem do tempo sem pagamento nao soma parcelas');
assert.strictEqual(run('parcelasPagasConfirmadas(S.cartao[3])'),0,'Mes seguinte nao presume pagamento de compra nova');
run("hoje='2026-09-20'");
run('S.cartao=S.cartao.slice(0,1)');
assert.strictEqual(run("getParcelasCartao().find(x=>x.id==='101-0').data"),'2026-09-10','Primeira parcela do hotel deve continuar em setembro');
assert.strictEqual(run("getParcelasCartao().find(x=>x.id==='101-1').data"),'2026-10-10','Segunda parcela deve continuar em outubro');
run("S.extrato.push({id:201,tipo:'saida',cardId:1,faturaMes:'2026-10',val:224.73,data:'2026-10-12'})");
assert.strictEqual(run('parcelasPagasConfirmadas(S.cartao[0])'),1,'Pagamento futuro nao confirma parcela hoje');
run("hoje='2026-10-20'");
assert.strictEqual(run('parcelasPagasConfirmadas(S.cartao[0])'),2,'Fatura quitada confirma segunda parcela');
run("S.extrato.push({id:202,tipo:'saida',cardId:1,faturaMes:'2026-11',val:100,data:'2026-10-19'})");
assert.strictEqual(run('parcelasPagasConfirmadas(S.cartao[0])'),2,'Pagamento parcial nao identifica compra quitada');
run("S.extrato.push({id:203,tipo:'saida',cardId:1,faturaMes:'2026-11',val:124.73,data:'2026-10-20'})");
assert.strictEqual(run('parcelasPagasConfirmadas(S.cartao[0])'),3,'Quitacao da fatura aumenta o progresso');
assert.strictEqual(run('totalDaFatura(1,"2026-10")'),22473,'Indicador nao deve alterar fatura');
assert.strictEqual(run('S.saldoInicial.valor'),1000,'Indicador nao deve alterar saldo inicial');
const payload=run('JSON.stringify({versao:2,dados:S})');
assert.strictEqual(run('validarDadosImportados('+JSON.stringify(JSON.parse(payload))+').cartao[0].parcelasPagasInformadas'),1,'JSON deve preservar progresso manual');
assert.throws(()=>run("validarDadosImportados({cartao:[{id:101,data:'2026-09-02',parcelas:6,parcelasPagasInformadas:7}],extrato:[],invest:[],cartoes:[]})"),'Nao aceitar quantidade paga maior que parcelas');
assert.throws(()=>run("validarDadosImportados({cartao:[{id:101,data:'2026-09-02',parcelas:6,parcelasPagasInformadas:1.5}],extrato:[],invest:[],cartoes:[]})"),'Nao aceitar parcelas fracionarias');
assert.strictEqual(run("validarDadosImportados({cartao:[{id:101,data:'2026-09-02',parcelas:6}],extrato:[],invest:[],cartoes:[]}).cartao.length"),1,'JSON antigo continua valido');
console.log('PASS: progresso manual e automatico das parcelas, contraste, JSON antigo e saldo preservado');
