const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('index.html','utf8'),js=fs.readFileSync('js/recorrentes.js','utf8');
assert(html.includes('<script src="js/recorrentes.js?v=20260920-conta2"></script>'),'Carregamento de recorrências ausente');
assert(html.includes('id="ext-gasto-tipo" aria-hidden="true"'),'Tipo fixo/variável não deve aparecer no Extrato');
assert(html.includes('id="cc-gasto-tipo" tabindex="-1"'),'Tipo fixo/variável não deve aparecer no Cartão');
assert(!/(?<![\w.])(?:alert|confirm|prompt)\s*\(/.test(js),'Não chamar caixas nativas');
const source=html.match(/<script\s*>([\s\S]*?)<\/script>/);
assert(source,'Script principal ausente');fs.writeFileSync('/tmp/meu-dinheiro-validar.js',source[1]);
const isoDate=(y,m,d)=>y+'-'+String(m+1).padStart(2,'0')+'-'+String(d).padStart(2,'0');
const dataISOValida=v=>{if(typeof v!=='string'||!/^\d{4}-\d\d-\d\d$/.test(v))return false;const d=new Date(v+'T12:00:00');return !Number.isNaN(d.getTime())&&isoDate(d.getFullYear(),d.getMonth(),d.getDate())===v;};
const ctx={Date,Error,Number,String,Array,Math,console,module:{exports:{}},isoDate,dataISOValida};
vm.runInNewContext(js,ctx);
const {proximaDataRecorrente,datasRecorrentes}=ctx.module.exports;
assert.strictEqual(proximaDataRecorrente('2026-01-31','mensal',1),'2026-02-28');
assert.strictEqual(proximaDataRecorrente('2026-01-31','mensal',2),'2026-03-31');
assert.strictEqual(proximaDataRecorrente('2026-09-18','semanal',1),'2026-09-25');
assert.strictEqual(proximaDataRecorrente('2024-02-29','anual',1),'2025-02-28');
assert.deepStrictEqual(Array.from(datasRecorrentes({inicio:'2026-08-05',frequencia:'mensal',fim:'2026-11-01'},'2026-12-31')),['2026-08-05','2026-09-05','2026-10-05']);
assert.deepStrictEqual(Array.from(datasRecorrentes({inicio:'2026-08-05',frequencia:'mensal',vigenteDesde:'2026-09-19'},'2026-11-30')),['2026-10-05','2026-11-05']);
for(const token of ['recorrenciaData','recorrenciaIgnoradas','saldoInicial.data','originalJaRegistrado','syncRecurring','cardForecasts','cashForecastsForMonth','deleteRec','openRecEditor','appConfirm'])assert(js.includes(token),'Regra ausente: '+token);
assert(js.includes("cardSection.id='rec-cartao-area'"),'Assinaturas precisam de área própria na aba Cartão');
assert(js.includes('id=\"rec-card-open\"'),'Botão de assinatura ausente');
assert(js.includes('r.excluida=true;r.fim=today()'),'Excluir deve suspender o futuro e preservar histórico');
assert(!js.includes('id=\"rec-end\"')&&!js.includes('data-reccancel'),'Campos duplicados de encerramento não devem aparecer');
assert(js.includes('cardRow.hidden=true;cardRow.remove()'),'Campo de cartão precisa sair fisicamente do formulário da conta');
assert(!js.includes('id=\"rec-end\"'),'Encerramento não pertence ao cadastro inicial');
assert(js.includes('data-recdelete=\"${r.id}\">Excluir agora'),'Exclusão deve estar na lista dos registros criados');
console.log('PASS: recorrências, separação conta/cartão, exclusão prospectiva, histórico e validação');
